---
- name: CRI Install
  hosts: all
  gather_facts: true
  roles:
    - {role: "common", tags: "containerd"}
    - {role: "runc", tags: "containerd"}
    - {role: "containerd", tags: "containerd", when: container_engine == "containerd"}
    - {role: "cni_plugins", tags: "containerd"}
    - {role: "crictl", tags: "containerd"}
    - {role: "buildkit", tags: "containerd", when: enable_buildkit}
    - {role: "rootlesskit", tags: "containerd", when: enable_rootlesskit}
