all:
  hosts:
    dev01:
      ansible_host: 192.168.123.5
      cni_subnet: "172.18.3.0/24"
    dev02:
      ansible_host: 192.168.123.6
      cni_subnet: "172.18.4.0/24"
  vars:
    container_engine: "containerd"
    enable_nerdctl: true
    enable_buildkit: true
    enable_rootlesskit: true
    enable_cpu_delegation: false