---
- name: Sysctl_reload
  become: true
  ansible.builtin.shell: 'sysctl --system'

- name: Apparmor_reload
  become: true
  ansible.builtin.systemd_service:
    name: apparmor
    daemon_reload: true
    state: restarted
