---
- name: Download and Install CNI plugins
  block:
  - name: Acquire CNI Plugins archive
    get_url:
      url: '{{ cni_plugin_url }}/{{ cni_plugin_archive }}'
      dest: '/tmp/{{ cni_plugin_archive }}'
      checksum: 'sha256:{{ cni_plugin_url }}/{{ cni_plugin_archive }}.sha256'
      mode: '0444'
  - name: Create target CNI directory
    file:
      path: '{{ cni_plugin_target }}'
      state: directory
      mode: '0755'
  - name: Extract plugins
    unarchive: 
      src: '/tmp/{{ cni_plugin_archive }}'
      dest: '{{ cni_plugin_target }}'
      remote_src: 'yes'
  - name: Cleanup plugin archive
    file:
      path: '/tmp/{{ cni_plugin_archive }}'
      state: absent
  become: true
