---
- name: Download and Install of cri-tools (crictl)
  block:
  - name: Acquire cri-tools archive
    get_url:
      url: '{{ cri_tools_url }}/{{ cri_tools_archive }}'
      dest: '/tmp/{{ cri_tools_archive }}'
      # newer releases post a sha256 file.
      #checksum: 'sha256:{{ cri_tools_url }}/{{ cri_tools_archive }}.sha256'
      checksum: 'sha256:{{ cri_tools_sha256 }}'
      mode: '0444'
  - name: Extract cri-tools
    unarchive:
      src: '/tmp/{{ cri_tools_archive }}'
      dest: '/usr/local/bin/'
      remote_src: 'yes'
      mode: '0755'
  - name: Configure crictl
    copy:
      src: 'crictl.yaml'
      dest: '/etc/crictl.yaml'
      mode: '0644'
  - name: Cleanup cri-tools archive
    file:
      path: '/tmp/{{ cri_tools_archive }}'
      state: absent
  become: true