---
- name: Download and Install 'nerdctl'
  block:
    - name: Acquire nerdctl
      get_url:
        url: '{{ nerdctl_url }}/{{ nerdctl_archive }}'
        dest: '/tmp/{{ nerdctl_archive }}'
        checksum: 'sha256:{{ nerdctl_sha256 }}'
        mode: '0444'
    - name: Extract nerdctl
      unarchive:
        src: '/tmp/{{ nerdctl_archive }}'
        dest: '/usr/local/bin'
        remote_src: 'yes'
        mode: '0755'
    - name: Cleanup nerdctl archive
      file:
        path: '/tmp/{{ nerdctl_archive }}'
        state: absent
  become: true

- name: Create Docker Link
  file:
    src: '/usr/local/bin/nerdctl'
    dest: '/usr/local/bin/docker'
    state: link
  become: true
  when: create_docker_link
