---
# note mismatched use of 'v' on version
containerd_version: '1.7.9'
containerd_url: 'https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}'
containerd_archive: 'containerd-{{ containerd_version }}-linux-amd64.tar.gz'
containerd_service_file : 'https://raw.githubusercontent.com/containerd/containerd/main/containerd.service'
containerd_service_target: '/etc/systemd/system/containerd.service'

runc_version: "v1.1.10"
runc_url: "https://github.com/opencontainers/runc/releases/download/{{ runc_version }}/runc.amd64"
runc_sha256: '81f73a59be3d122ab484d7dfe9ddc81030f595cc59968f61c113a9a38a2c113a'

cni_plugin_version: 'v1.3.0'
cni_plugin_url: 'https://github.com/containernetworking/plugins/releases/download/{{ cni_plugin_version }}'
cni_plugin_archive: 'cni-plugins-linux-amd64-{{ cni_plugin_version }}.tgz'
cni_plugin_target: '/opt/cni/bin'

cri_tools_version: 'v1.28.0'
cri_tools_url: 'https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ cri_tools_version }}'
cri_tools_archive: 'crictl-{{ cri_tools_version }}-linux-amd64.tar.gz'
cri_tools_sha256: '8dc78774f7cbeaf787994d386eec663f0a3cf24de1ea4893598096cb39ef2508'

# note mismatched use of 'v' on version
nerdctl_version: '1.7.0'
nerdctl_url: 'https://github.com/containerd/nerdctl/releases/download/v{{ nerdctl_version }}'
nerdctl_archive: 'nerdctl-{{ nerdctl_version }}-linux-amd64.tar.gz'
nerdctl_sha256: '844c47b175a3d6bc8eaad0c51f23624a5ef10c09e55607803ec2bc846fb04df9'
nerdctl_full_archive: 'nerdctl-full-{{ nerdctl_version }}-linux-amd64.tar.gz'
nerdctl_full_sha256: '8a3bdc24eef1b7366a678f206aff37ce7ae22f184ad24ed723a92420796b68ca'

buildkit_version: 'v0.12.3'
buildkit_url: 'https://github.com/moby/buildkit/releases/download/{{ buildkit_version }}'
buildkit_archive: 'buildkit-{{ buildkit_version }}.linux-amd64.tar.gz'

rootlesskit_version: 'v1.1.1'
rootlesskit_url: 'https://github.com/rootless-containers/rootlesskit/releases/download/{{ rootlesskit_version }}'
rootlesskit_archive: 'rootlesskit-x86_64.tar.gz'
rootlesskit_sha256: '3c83affbb405cafe2d32e2e24462af9b4dcfa19e3809030012ad0d4e3fd49e8f'

slirp4netns_version: 'v1.2.2'
slirp4netns_url: 'https://github.com/rootless-containers/slirp4netns/releases/download/{{ slirp4netns_version }}'
slirp4netns_binary: 'slirp4netns-x86_64'
slirp4netns_sha256: '2b59dd438ec1814dcd00c3106c0288ca174c3fe9a178f3400baa06818edaae8d'

cri_apt_packages:
  - net-tools
  - ethtool
  - bridge-utils
  - uidmap

cri_yum_packages:
  - ethtool
  - bridge-utils
  - uidmap