---
- name: Install dependencies (Debian/Ubuntu)
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS'
  ansible.builtin.apt:
    name: '{{ cri_apt_packages }}'
    state: present

- name: Install dependencies (RHEL/Ubuntu)
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  block:
    - name: Install yum packages
      ansible.builtin.apt:
        name: '{{ cri_apt_packages }}'
        state: present

- name: Delegate cpuset
  ansible.builtin.include_tasks: 'cpuset-delegation.yml'
  when: enable_cpu_delegation
