---
cri_ansible_version: 'v26.10.10'

# note mismatched use of 'v' on version is intentional
containerd_version: '2.4.1'
containerd_url: 'https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}'
containerd_archive: 'containerd-{{ containerd_version }}-linux-amd64.tar.gz'
containerd_sha256: '{{ containerd_url }}/{{ containerd_archive }}.sha256sum'
containerd_service_file: 'https://raw.githubusercontent.com/containerd/containerd/main/containerd.service'
containerd_service_target: '/etc/systemd/system/containerd.service'

runc_version: "v1.5.2"
runc_url: "https://github.com/opencontainers/runc/releases/download/{{ runc_version }}/runc.amd64"
runc_sha256: '599f6f94ff8c5057241eff0d54c3c74f95c34935b6457b33fe545defc61e9488'

cni_plugin_version: 'v1.9.1'
cni_plugin_url: 'https://github.com/containernetworking/plugins/releases/download/{{ cni_plugin_version }}'
cni_plugin_archive: 'cni-plugins-linux-amd64-{{ cni_plugin_version }}.tgz'
cni_plugin_sha256: '{{ cni_plugin_url }}/cni-plugins-linux-amd64-{{ cni_plugin_version }}.tgz.sha256'
cni_plugin_target: '/opt/cni/bin'

cri_tools_version: 'v1.37.0'
cri_tools_url: 'https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ cri_tools_version }}'
cri_tools_archive: 'crictl-{{ cri_tools_version }}-linux-amd64.tar.gz'
cri_tools_sha256: '{{ cri_tools_url }}/{{ cri_tools_archive }}.sha256'

# note intentional mismatched use of 'v' on version
nerdctl_version: '2.4.1'
nerdctl_url: 'https://github.com/containerd/nerdctl/releases/download/v{{ nerdctl_version }}'
nerdctl_archive: 'nerdctl-{{ nerdctl_version }}-linux-amd64.tar.gz'
nerdctl_sha256: 'f6bbf02fd8a299cbcbc71a0bad113c1b63b3f33689bbb7d51b0fa98c6d361d5e'
nerdctl_full_archive: 'nerdctl-full-{{ nerdctl_version }}-linux-amd64.tar.gz'
nerdctl_full_sha256: 'ff018f11ac2f1354bf7b3aaaca6e0b52d81139c746a89134744d0b7be3a0e62f'

buildkit_version: 'v0.34.0'
buildkit_url: 'https://github.com/moby/buildkit/releases/download/{{ buildkit_version }}'
buildkit_archive: 'buildkit-{{ buildkit_version }}.linux-amd64.tar.gz'
buildkit_sha256: '14813b1fb2a40082114e6d386c6fc5e7dd5298176ce7ee1a18bc33e73e109ac3'

rootlesskit_version: 'v3.2.0'
rootlesskit_url: 'https://github.com/rootless-containers/rootlesskit/releases/download/{{ rootlesskit_version }}'
rootlesskit_archive: 'rootlesskit-x86_64.tar.gz'
rootlesskit_sha256: 'ff612d1d35854a52569acc4a4e9152f41504e69dcc13ff4c94cc9040dc28b3d9'

slirp4netns_version: 'v1.3.6'
slirp4netns_url: 'https://github.com/rootless-containers/slirp4netns/releases/download/{{ slirp4netns_version }}'
slirp4netns_binary: 'slirp4netns-x86_64'
slirp4netns_sha256: '411167abceff1fc8a7c562f53ed9f26d3ec8a17df4e2fe6eaa3bd53f1c1e1d48'

cri_apt_packages:
  - net-tools
  - ethtool
  - bridge-utils
  - uidmap

cri_yum_packages:
  - ethtool
  - bridge-utils
  - uidmap
