name: Ansible Lint

on:
  push:
    tags: [ "v*" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Ansible Lint
        uses: ansible/ansible-lint@v6.22.2
        with:
          args: --force-color
