---
- name: Download and Install containerd
  become: true
  block:
    - name: Acquire containerd archive
      ansible.builtin.get_url:
        url: '{{ containerd_url }}/{{ containerd_archive }}'
        dest: '/tmp/{{ containerd_archive }}'
        checksum: 'sha256:{{ containerd_sha256 }}'
        mode: '0444'
    - name: Extract containerd archive
      ansible.builtin.unarchive:
        src: '/tmp/{{ containerd_archive }}'
        dest: '/usr/local'
        remote_src: 'yes'
    - name: Cleanup containerd archive
      ansible.builtin.file:
        path: '/tmp/{{ containerd_archive }}'
        state: absent
    - name: Create containerd config dirs
      ansible.builtin.file:
        path: '/etc/containerd/certs.d'
        state: directory
        mode: '0755'
    - name: Configure containerd
      ansible.builtin.shell: 'containerd config default > /etc/containerd/config.toml'
    - name: Install service config (system)
      ansible.builtin.copy:
        src: 'containerd.service'
        dest: '/etc/systemd/system/containerd.service'
        mode: '0644'
    - name: Enable systemd service
      ansible.builtin.systemd:
        name: 'containerd'
        daemon_reload: true
        enabled: true
        state: started

- name: Install system CNI config
  become: true
  ansible.builtin.template:
    src: '10-cri-net.conf.j2'
    dest: '/etc/cni/net.d/10-cri-net.conf'
    mode: '0644'

- name: Set userspace CNI config
  become: true
  when: set_user_cni_config and enable_rootlesskit
  block:
    - name: Ensure user CNI config dir exists
      ansible.builtin.file:
        path: '~/.config/cni/net.d'
        state: directory
        mode: '0755'
    - name: Configure userspace CNI
      ansible.builtin.template:
        src: '10-cri-net.conf.j2'
        dest: '~/.config/cni/net.d/10-cri-net.conf'
        mode: '0644'

- name: Configure Private Registry
  become: true
  when: registry_host
  block:
    - name: Create Registry path
      ansible.builtin.file:
        path: '/etc/containerd/certs.d/{{ registry_host }}'
        state: directory
        mode: '0755'
    - name: Create Registry hosts config
      ansible.builtin.template:
        src: 'hosts.toml.j2'
        dest: '/etc/containerd/certs.d/{{ registry_host }}/hosts.toml'
        mode: '0644'

- name: ContaiNerdctl
  ansible.builtin.include_tasks: "nerdctl.yml"
  when: enable_nerdctl or enable_rootlesskit
